---
# tasks file for directus

- name: Configuring postgres

  block:
        
    # copy compose file to server
    # --
    # 
    - name: Copy compose file to server
      ansible.builtin.template:
        src: "templates/docker-compose.yml.jinja2"
        dest: "{{ user_home_dir }}/.postgres/docker-compose.yaml"


    # deploy directus stack
    # --
    #
    - name: Docker Compose Up 
      community.docker.docker_compose:
          project_src: ".postgres"
        
      register: output


    - name: Debug output
      ansible.builtin.debug:
        var: output
